name: EAS Build
on:
  workflow_dispatch:
  push:
    branches:
      - v[0-9]+
jobs:
  setup:
    name: Setup EAS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
  build:
    needs: setup
    name: Install and build preview
    runs-on: ubuntu-latest
    steps:
      - name: Build on EAS
        run: eas build --platform all --non-interactive --profile preview
  update:
    needs: setup
    name: Publish EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Publish EAS Update
        run: eas update --branch preview
